export default {
	extends: ["stylelint-config-standard"],
	rules: {
		"alpha-value-notation": null,
		"color-function-alias-notation": null,
		"color-function-notation": null,
		"color-hex-length": null,
		"custom-property-empty-line-before": null,
		"declaration-block-no-redundant-longhand-properties": null,
		"declaration-block-no-shorthand-property-overrides": null,
		"declaration-empty-line-before": null,
		"declaration-property-value-keyword-no-deprecated": null,
		"length-zero-no-unit": null,
		"no-descending-specificity": null,
		"property-no-vendor-prefix": null,
		"rule-empty-line-before": null,
		"selector-class-pattern": null,
		"selector-not-notation": null,
		"value-keyword-case": null,
	},
};
