export const STICKY_NOTE_FLOAT_DEFAULT_WIDTH = 292;
export const STICKY_NOTE_FLOAT_DEFAULT_HEIGHT = 119;
export const STICKY_NOTE_FLOAT_MIN_WIDTH = 220;
export const STICKY_NOTE_FLOAT_MIN_HEIGHT = 100;
export const STICKY_NOTE_FLOAT_LEFT_GAP = 14;
