export const UI = {
	ICON: {
		PLUGIN: "book-type",
		STICKY_NOTE: "lightbulb",
		SPARKLES: "sparkles",
		FILE: "file-text",
		H1: "heading-1",
		H2: "heading-2",
		H3: "heading-3",
		H4: "heading-4",
		H5: "heading-5",
		H6: "heading-6",
		EXPAND: "list-chevrons-up-down",
		COLLAPSE: "list-chevrons-down-up",
		ADD_TO_GUIDEBOOK: "book-plus",
		REMOVE_FROM_GUIDEBOOK: "book-minus",
		CHEVRON_UP: "chevron-up",
		CHEVRON_DOWN: "chevron-down",
		CHEVRON_RIGHT: "chevron-right",
		CHEVRON_LEFT: "chevron-left",
		CALENDAR_ARROW_DOWN: "calendar-arrow-down",
		CALENDAR_ARROW_UP: "calendar-arrow-up",
		SETTING: "gear",
		SEND: "send-horizontal",
		CLEAN: "brush-cleaning",
		DELETE: "trash-2",
		PIN: "pin",
		ELLIPSIS: "ellipsis",
		FOLDER_PLUS: "folder-plus",
		PENCIL: "pencil",
		SEARCH: "search",
		GRIP_VERTICAL: "grip-vertical",
		CLOSE: "x",
		PLUS: "plus",
		BOLD: "bold",
		ITALIC: "italic",
		STRIKETHROUGH: "strikethrough",
		HIGHLIGHTER: "highlighter",
		LIST: "list",
		LIST_ORDERED: "list-ordered",
		ERASER: "eraser",
		FUNNEL: "funnel-plus",
		BOOKMARK: "message-square-text",
		MAP_PIN: "map-pin",
	},
} as const;

export const STICKY_NOTE_COLORS = [
	"#4A86E9",
	"#7B61FF",
	"#47B881",
	"#F6C445",
	"#F59E0B",
	"#F05D6C",
	"#9CA3AF",
] as const;
